module.exports = {
  menu: require("./menu.js"),
  ownerContact: require("../configs/ownerContact.js"),
  info: require("../configs/info.json"),
  makeSticker: require("./stickers/createSticker.js"),
  stkToMedia: require("./stickers/stickerToMedia.js"),
  profile: require("./informations/profile.js"),
  infoBot: require("./informations/infoBot.js"),
  sendSugestionToBotOwner: require("./informations/sugestions.js"),
  editBotFiles: require("./owner/editBotFiles.js"),
  ytDownload: require("./downloads/ytDownload.js"),
  igDownload: require("./downloads/igDownload.js"),
  tkkDownload: require("./downloads/tkkDownload.js"),
  sendText: require("../utils/message.js").sendText,
  getMessageText: require("../utils/message.js").getMessageText,
  sendVideo: require("../utils/message.js").sendVideo,
  isQuotedImage: require("../utils/media.js").isQuotedImage,
  isQuotedVideo: require("../utils/media.js").isQuotedVideo,
  isQuotedSticker: require("../utils/media.js").isQuotedSticker,
  getMediaMessageContent: require("../utils/media.js").getMediaMessageContent,
  selectQuote: require("../configs/personalizedQuotes.js"),
  printLogs: require("../utils/commands.js").printLogs
};
